### ISSUE TITLE
Adding Qt dependencies

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/docker-images#1]
Not sure if I have the right repo. Sorry still figuring this stuff out. :)

So, I have a recipe that uses Qt, but it is missing some dependencies like `libXext.so.6`. Would be nice to add these to the image.

cc @jjhelmus, I think I saw one of your feedstocks (don't remember which one) adds this stuff explicitly. Is that the way we should do this or can we add them to the docker image?

**Comment by jjhelmus** [comment]
The new Docker image will include `libXext.so.6` if you don't mind waiting.  Using the current image you need to yum install this library in the feedstock in the `ci_support/run_docker_build.sh` file, as in conda-forge/wradlib-feedstock#1.  If/when the feedstock is re-rendered this change will be lost, see conda-forge/wradlib-feedstock#2

**Comment by jakirkham** [comment]
No problem waiting. Though I will need to use your workaround in the interim. Thanks for the pointers.

**Comment by jakirkham** [comment]
We have already decided to add these to the current image. Closing...
