### ISSUE TITLE
Dropping legacy conda-forge/linux-anvil

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/docker-images#101]
Given we have migrated the stack to the newer `conda-forge/linux-anvil-comp7` (and derivatives) and we are not maintaining the legacy [`conda-forge/linux-anvil` image]( https://github.com/conda-forge/docker-images/tree/master/linux-anvil ), should we go ahead and remove it from this repo?

**Comment by scopatz** [comment]
Are we actually rebuilding it?

**Comment by jakirkham** [comment]
Yep 😄

https://github.com/conda-forge/docker-images/blob/5e9e1a13ed76f55e48ba59eacbd795ef71cb8bb7/.travis.yml#L5-L13

**Comment by scopatz** [comment]
Oh yeah, let's drop building that

**Comment by jakirkham** [comment]
Appears we were testing it too. PR ( https://github.com/conda-forge/docker-images/pull/104 ) switches CircleCI to testing our newer base image.

**Comment by jakirkham** [comment]
Resolving with PR ( https://github.com/conda-forge/docker-images/pull/105 ).
