### ISSUE TITLE
Proposal: Add system wide perl installation to condaforge/linux-anvil-comp7

### ISSUE THREAD

**Issue by andersy005** [conda-forge/docker-images#110]
Issue: It appears that there's no system wide `Perl` installation in condaforge/linux-anvil-comp7.  This is not really a big deal since `Perl` is installed in the base environment:

```bash
[conda@7cf862609754 ~]$ which perl
/opt/conda/bin/perl
```

However, I found out that some applications look for perl in specific locations, namely `/usr/bin/perl`. For e.g: The cuda-toolkit installer expects to find `Perl` in `/usr/bin/perl`: https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/11
```bash
/opt/conda/pkgs/cudatoolkit-dev/cuda_10.0.130_410.48_linux: ./cuda-installer.pl: /usr/bin/perl: bad interpreter: No such file or directory
```
I am wondering whether there exists a simple fix here or whether this would require having a system wide Perl installation as part of the docker image?

**Comment by h-vetinari** [comment]
I thought this should be solvable with `yum_requirements.txt` containing "perl", but this [did not get picked up](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=50089) by the docker build with `linux-anvil-comp7`.

**Comment by h-vetinari** [comment]
Update: didn't know that azure only picks up `yum_requirements.txt` after rerendering the recipe. I think this issue can be closed. :)

**Comment by scopatz** [comment]
I have to say that I am pretty against adding things to the docker containers, since we should try to keep them as small as possible

**Comment by andersy005** [comment]
Okie dokie... 

> Update: didn't know that azure only picks up yum_requirements.txt after rerendering the recipe. I think this issue can be closed. :)

Glad to know that this fix solves the issue...

> we should try to keep them as small as possible

I concur. I just wasn't aware of the above fix by @h-vetinari
