### ISSUE TITLE
Error with powerpc image

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/docker-images#115]
[Getting the following error on travis:](https://travis-ci.com/conda-forge/pycurl-feedstock/jobs/244222442#L271)
```
Status: Downloaded newer image for condaforge/linux-anvil-ppc64le:latest
standard_init_linux.go:190: exec user process caused "exec format error"
```
It seems that this is because the image is lacking bash? https://github.com/containers/buildah/issues/475#issuecomment-484019387

**Comment by jakirkham** [comment]
cc @jayfurmanek

**Comment by jakirkham** [comment]
Yep, looks like that is the same case here. To summarize, travis-ci.com does not support ppc64le, but travis-ci.org does. Happy to close @CJ-Wright?

**Comment by jayfurmanek** [comment]
yeah - this is the .com/.org thing again. `exec format error` is the error you get when running ppc code on non-ppc hw (or emulation env).  We don't really know why this happens sometimes.
I've been told .com will have ppc systems too at some point, but I have no timeframe to share.

**Comment by jakirkham** [comment]
It’s already good to hear that Travis CI plans to add ppc64le to `.com`.
