### ISSUE TITLE
Consider renaming "jnlp-slave" docker config

### ISSUE THREAD

**Issue by mrakitin** [conda-forge/docker-images#143]
Please consider renaming the `jnlp-slave` Docker config and the corresponding image name(s). Some background: https://bugs.python.org/issue34605. Thank you.

**Comment by scopatz** [comment]
PRs welcome! And I totally agree!

**Comment by beckermr** [comment]
These files were removed so I think we can close this issue. @isuruf?

**Comment by jakirkham** [comment]
Yes they were removed. Closing...
