### ISSUE TITLE
No unzip in circle-ci image

### ISSUE THREAD

**Issue by jochym** [conda-forge/docker-images#15]
The image for circle-ci (centos I believe) has no unzip command available. I think it would be useful to add it. E.g. github downloads are zip by default (and it is not that easy to find how to get a tarball).

**Comment by jakirkham** [comment]
Please see this PR ( https://github.com/conda-forge/docker-images/pull/20 ), which should change this.

**Comment by pelson** [comment]
Hi @jochym. We decided to close #20 as we had some concerns about adding extra packages into the image and that potentially masking build dependencies of packages that get built. Whilst it is convenient to have the build image available for interactive build testing (I do this too), I want to make sure our image is as pristine as we can make it. Hope that works for you. 

If not, one option would be to add this dependency on top of the linux-anvil image with your own Dockerfile. I'm sure you already know this, but it is an excellent way of specialising a useful image, and would work well in this case (may even work well as a conda-forge hosted thing, but let's not run before we can walk).
