### ISSUE TITLE
move to azure

### ISSUE THREAD

**Issue by beckermr** [conda-forge/docker-images#176]
This build is pretty hefty so we should move it to azure.

**Comment by beckermr** [comment]
cc @xhochy

**Comment by jakirkham** [comment]
Given the increasing predominance of GHA, is this still worth pursuing?

If so, do we have a sense of the current costs of using GHA here compared to Azure?

**Comment by beckermr** [comment]
It's probably best to not do it since we have so much work invested in the GHA ci.

**Comment by jakirkham** [comment]
Ok will close as won't fix. If that changes, we can always revisit
