### ISSUE TITLE
Including mamba in base images

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/docker-images#188]
More and more, I'm finding that conda is starting to fail to find solutions to environments. I'm not sure if it is because I have channels other than conda-forge enabled

is it time to start including `mamba` in the anvil images so as to speed up build time on systems?

**Comment by jakirkham** [comment]
No objections from me

@conda-forge/core does anyone else have thoughts on this?

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/docker-images/pull/193 )
