### ISSUE TITLE
Instant segfault for linux-anvil-comp7 on WSL2 

### ISSUE THREAD

**Issue by davidhewitt** [conda-forge/docker-images#199]
FYI I was trying to run `linux-anvil-comp7` this morning from a WSL2 (ubuntu) environment, and had to employ the workaround in https://github.com/microsoft/WSL/issues/4694#issuecomment-556095344 to avoid an immediate docker exit with code 139.

Not sure if there's much that should be done about this, hopefully this note helps others with the same problem.

**Comment by jakirkham** [comment]
Do you have the same issue with CentOS 7 based images?

**Comment by davidhewitt** [comment]
CentOS 7 images work without problem.

Just noticed there is also information about this CentOS 6 drawback at https://hub.docker.com/_/centos. (See section "A note about vsyscall".)

**Comment by jakirkham** [comment]
Great!

Yeah wouldn't spend much more time thinking about CentOS 6. We moved the default image to CentOS 7 ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2241 ).

**Comment by davidhewitt** [comment]
Great, in which case let's close this!

**Comment by jakirkham** [comment]
Thanks David! 😄
