### ISSUE TITLE
centos images & user+mnt namespaces

### ISSUE THREAD

**Issue by ngam** [conda-forge/docker-images#203]
I am not really sure how to even go about figuring this out, but I am not sure why a script in this build cannot see the user and mount namespaces enabled inside the centos containers. The charliecloud script automatically scans for these two namespaces to determine what to build (ch-image, etc.)

```
Running containers
~~~~~~~~~~~~~~~~~~

  ch-run(1): no
    user+mount namespaces ... no
```

https://github.com/conda-forge/staged-recipes/pull/17238

This is weird, because I am usually accustomed to checking namespaces via `lsns` and this is what you'd get inside the centos containers:

```bash
~$ docker run -it quay.io/condaforge/linux-anvil-comp7      
[conda@34b6d87eaaa6 ~]$ lsns
bash: lsns: command not found
[conda@34b6d87eaaa6 ~]$ 

``` 

```bash
~$ docker run -it condaforge/mambaforge
(base) root@f9d1f441da16:/# lsns
        NS TYPE   NPROCS PID USER COMMAND
4026531837 user        3   1 root tini -- /bin/bash
4026532372 mnt         3   1 root tini -- /bin/bash
4026532373 uts         3   1 root tini -- /bin/bash
4026532374 ipc         3   1 root tini -- /bin/bash
4026532375 pid         3   1 root tini -- /bin/bash
4026532377 net         3   1 root tini -- /bin/bash
4026532453 cgroup      3   1 root tini -- /bin/bash
```

```bash
$ docker run -it quay.io/condaforge/linux-anvil-cos7-x86_64
[conda@7ca974e6e3a7 ~]$ lsns
        NS TYPE  NPROCS PID USER  COMMAND
4026531837 user       2   7 conda /usr/bin/qemu-x86_64 /bin/bash
4026532287 mnt        2   7 conda /usr/bin/qemu-x86_64 /bin/bash
4026532288 uts        2   7 conda /usr/bin/qemu-x86_64 /bin/bash
4026532289 ipc        2   7 conda /usr/bin/qemu-x86_64 /bin/bash
4026532290 pid        2   7 conda /usr/bin/qemu-x86_64 /bin/bash
4026532292 net        2   7 conda /usr/bin/qemu-x86_64 /bin/bash
```

Anyway, any experience with this or any immediate thoughts?

---

- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ngam** [comment]
update: adding     `- sysroot_linux-64 2.17  # [linux64]` + the centos7 spec fixes this issue. Closing.

**Comment by timsnyder** [comment]
I think part of this problem is user namespaces are disabled by default in Centos7... I'm going to see if we can get them enabled.
