### ISSUE TITLE
CUDA 11.0+ PPC & ARM builds failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/docker-images#208]
Seeing the following failure on the CUDA 11.0+ images for PPC & ARM. Snippet taken from [one CI build]( https://github.com/conda-forge/docker-images/runs/5262962163?check_suite_focus=true#step:6:124 ) below:

```
Step 17/26 : RUN yum update -y --disablerepo=cuda &&     yum install -y         bzip2         sudo         tar         which         &&     /opt/docker/bin/yum_clean_all
Warning: rning] The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 484977595ef4
CentOS Linux 8 - AppStream                       84  B/s |  38  B     00:00    
Failed to set locale, defaulting to C.UTF-8
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
The command '/bin/sh -c yum update -y --disablerepo=cuda &&     yum install -y         bzip2         sudo         tar         which         &&     /opt/docker/bin/yum_clean_all' returned a non-zero code: 1
```

Note the first build that passes is [this one from 25 days ago]( https://github.com/conda-forge/docker-images/actions/runs/1767881750 ).

**Comment by jaimergp** [comment]
Timeline matches this [post](https://forums.centos.org/viewtopic.php?f=54&t=78708). COS8 is EOL :(

**Comment by jakirkham** [comment]
Thanks Jaime 🙂 Makes sense

Is there a way to ignore the errors? Would be good to keep these functional (even though CentOS has moved on)

**Comment by jaimergp** [comment]
I believe we need to change the repo urls to the "vault", as explained in this [post](https://forums.centos.org/viewtopic.php?p=330798#p330798):

```
sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
yum clean all
yum update -y
```

That will allow us to stay up-to-date (up to Dec 31st 2021). It might not last long, though.

**Comment by jakirkham** [comment]
Yeah was looking at that

**Comment by jakirkham** [comment]
A related question is how the `nvidia` base images may change due to this

One option for us would be to switch the to [RHEL UBIs]( https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image ), which are also available. Though not sure how this will affect usage of `yum`

**Comment by jakirkham** [comment]
Have gone ahead with CentOS Vault in PR ( https://github.com/conda-forge/docker-images/pull/211 ). This seems like the easiest path to get things working again. As it is a snapshot of CentOS 8, it should be equivalent to the current images. So has the same tradeoffs those images have (EOL). This should at least unblock builds here and allow us to fix images as needed. However we may still want to find a better solution.
