### ISSUE TITLE
can we move all biz to userspace?

### ISSUE THREAD

**Issue by ngam** [conda-forge/docker-images#213]
### Comment:

Quite a bit of stuff in here lives in non-userspaces, e.g. `/opt`. This is almost never an issue with Docker, but is a bit of a pain when it comes to non-Docker alternatives, e.g. Singularity. 

1. Do we really need our main conda installation to live in `/opt`?
2. How about we move everything to `$HOME`?

Some discussion: https://github.com/conda-forge/conda-smithy/pull/1623. I can initiate a PR here at some point, but a lot of stuff is hardcoded, so it will take a bit of work... 

Edit: my bad, this is actually moot and won't work, I think. So I will close once I finish the conversation in the comments.

**Comment by jakirkham** [comment]
Can you please explain why `/opt` is hard for Singularity? Asking in part as I recall using these images with Singularity in the past and not recalling this specific issue (though things could have changed since then)

**Comment by ngam** [comment]
Good question! I am actually wrong, because moving things to `$HOME` won't make a difference... so this is moot. Below is more explanation.

**Comment by ngam** [comment]
I am by no means an expert, but here's my understanding:

Singularity defaults to read-only mode except for the directories on the host that the user mounts. This effectively means that there is no way for the user to edit anything inside the container in normal operations. The idea, in my understanding, is that one should use the container as a piece of software not to be edited. (There's one alternative, sandboxing, I will mention at the end.)

Because of the above, the way Singularity works nowadays is basically to mount a selection of directories (e.g. `$HOME`, `/tmp`, etc.) so that the user can make use of the containers. However, this proves an issue for conda-forge because there would no isolation anymore. To be concrete, it would mean that the conda inside the container will create an environment on the host (my computer) in my userspace (usually `~/.conda`). So we turn this "mounting stuff by default" off with the `-C` option, which instructs Singularity to isolate the container and not mount the host's directories. 

Now, we return to the issue, the conda inside the image is in `/opt`. The user can read it, but cannot write anything inside the image as long as the `-C` option is passed. The only solution is to mount some other directory to operate in, and map it to somewhere where the user has write access on the host, then the user can write in that directory from inside the container --- the writing happens on the host.

The alternative is sandboxing, but sandboxing is basically converting the image into a folder and that means we need to worry about storage and all sorts of problems that come with it. Incidentally, this is the only way to actually make use of conda-forge's Singularity and SingularityCE (they only work with sandboxing since we build them with non-admin rights). I tried looking into sandboxing images carefully, but it didn't go far, but my goal is to make this work with sandboxing eventually, because in that case we can do the whole thing with in-house tools.

**Comment by ngam** [comment]
Official word: https://sylabs.io/guides/3.9/user-guide/singularity_and_docker.html#read-only-by-default

**Comment by jakirkham** [comment]
Ah right. Thanks for all the details

Yeah think how I handled this before was to create new environments in the home directory, which worked well

Think in conda-forge we are expecting we can update the Conda `base` environment, which may cause issues. So maybe we make these lines optional or something. We do rebuild the containers weekly. So they are reasonably up-to-date

Conda-Build is configured to use `build_artifacts` for all build content (environments, packages, source cache, etc.), which is externally mounted. So that could be wherever is convenient for us
