### ISSUE TITLE
Latest anvil image installs incompatible conda and mamba versions

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/docker-images#223]
### Comment:

As mentioned in this comment: https://github.com/conda-forge/docker-images/pull/220#pullrequestreview-1132892021

A particular sequence of commands is making it so that 
* conda 22.9
* mamba 0.24 

```
$ docker run quay.io/condaforge/linux-anvil-cos7-x86_64 mamba --version
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
mamba 0.24.0
conda 22.9.0
```
are installed together. This configuration has been deemed incompatible upstream (see https://github.com/mamba-org/mamba/issues/1950). And was incompatible at the time of release.

I see a few ways forward:

1. Install a version, that on paper, is compatible between conda + mamba + boa: This is behind https://github.com/conda-forge/miniforge/pull/362
2. Uses tests to ensure that conda + mamba + boa are compatible: This is the idea behind behind https://github.com/conda-forge/miniforge/pull/361 however, for some reason, I see to be hitting cache issues.

Ultimately, I have been somewhat stuck trying to ensure a consistent environment in a few downstream projects. I've mostly reverted away from using anvil images as my solution (and that may be the recommend solution by others), but it means that the anvil images are somewhat broken at this stage.

I hope that the latest images can be reverted while we fix the issues in miniforge, ensuring that the anvil images stay with a working combination of conda+mamba.

**Comment by jakirkham** [comment]
Given PR ( https://github.com/conda-forge/docker-images/pull/224 ) is in, is this still an issue, Mark?
