### ISSUE TITLE
Updating QEMU

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/docker-images#226]
QEMU [7.2rc1]( https://www.phoronix.com/news/QEMU-7.2-rc1-Released ) has some notable performance improvements. Currently we are using 6.1.0. May be worth updating once that release is finalized to see how this improves build times.

https://github.com/conda-forge/docker-images/blob/8c37ae2a68e601ce55e8fce209170fd149a182b8/download-qemu-static.sh

**Comment by jakirkham** [comment]
cc @mariusvniekerk (who may have thoughts here)

**Comment by mariusvniekerk** [comment]
generally updating these has been pretty painless

**Comment by mariusvniekerk** [comment]
Is it worth upgrading to 7.1.0-2 ?

**Comment by jakirkham** [comment]
Maybe? Haven't specifically looked at that one

Interesting QEMU released [7.2.0-rc4]( https://github.com/qemu/qemu/releases/tag/v7.2.0-rc4 ) 6 days ago. Looks like historically a final release has followed pretty soon after. So may see 7.2.0 quite soon

**Comment by mariusvniekerk** [comment]
Opened #227 to get to 7.1.0
