### ISSUE TITLE
Centos 7 EOL, needs update to `vault` to install SCL 

### ISSUE THREAD

**Issue by hmacdope** [conda-forge/docker-images#277]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As cos7 is now EOL (30 Jun 2024), you need to use the `https://vault.centos.org/` instead of `http://mirrorlist.centos.org/` to install things with yum. eg. 

```
sudo yum install -y centos-release-scl epel-release 
```

See here for example fix:
https://github.com/apache/arrow/pull/43127/files

Happy to PR if you want to accept the fix, just let me know. 

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by jakirkham** [comment]
This was already done. Please see PR: https://github.com/conda-forge/docker-images/pull/271

**Comment by hmacdope** [comment]
Apologies, perhaps my image was cached.

**Comment by jakirkham** [comment]
No worries

Could be. Also if it is related feedstock, please try re-rendering

If you still see issues, it would be good to have a new issue with your setup for further debugging

**Comment by hmacdope** [comment]
Ah ok I think I understand the issue now. 

I am using the `condaforge/linux-anvil-cuda:11.2` older image which in the context of https://conda-forge.org/news/2024/03/06/dropping-cuda-112/ I understand is no longer supported, and in which the patch has not been applied. (image last updated 3 months ago). 

I will migrate to the 11.8 image, which AFAIk has the same device compatibility.

**Comment by jakirkham** [comment]
Correct it is not supported. Please migrate to CUDA 11.8
