### ISSUE TITLE
The cache user directory is non-writable (owned by root).

### ISSUE THREAD

**Issue by hadim** [conda-forge/docker-images#283]
### Comment:

The cache user directory (`/home/conda/.cache`) is non-writable (owned by root).

I noticed this while building locally from a feedstock `bash .scripts/run_docker_build.sh` using rattler-build and got the below error:

```
 ╰─────────────────── (took 8 seconds)
 × error Error building package: Failed to resolve dependencies: failed to acquire a lock on the repodata cache
Error:   × Failed to resolve dependencies: failed to acquire a lock on the repodata cache
  ├─▶ failed to acquire a lock on the repodata cache
  ├─▶ failed to open: /home/conda/.cache/rattler/cache/repodata/3018e552.lock
  ╰─▶ Permission denied (os error 13)
```

You can check the permissions of the cache folder with:

```
$ docker run --rm -ti quay.io/condaforge/linux-anvil-cos7-x86_64:latest ls -la /home/conda/.cache 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
total 12
drwxr-xr-x 3 root  root  4096 Oct  1 22:06 .
drwx------ 3 conda conda 4096 Oct  1 22:06 ..
drwxr-xr-x 2 root  root  4096 Oct  1 22:06 rosetta
```

The cache folder in the image is empty except for one **empty** folder called `rosetta/`.

I am not sure from where this `root` permission is coming from and what is this `rosetta/` folder as well.

**Comment by hadim** [comment]
Maybe worth noting, I am running the docker build from a macOS Silicon laptop.

**Comment by hadim** [comment]
Ok so it seems to be macOS specific....

On a Linux machine:

```
docker run --rm -ti quay.io/condaforge/linux-anvil-cos7-x86_64:latest ls -la /home/conda/
total 24
drwx------ 2 conda conda 4096 Oct  1 22:20 .
drwxr-xr-x 1 root  root  4096 Oct  1 22:20 ..
-rw-r--r-- 1 conda conda   18 Nov 24  2021 .bash_logout
-rw-r--r-- 1 conda conda  193 Nov 24  2021 .bash_profile
-rw-r--r-- 1 conda conda  231 Nov 24  2021 .bashrc
-rw-r--r-- 1 conda conda   75 Oct  1 22:20 .condarc
```

It's not a c-f bug, so I will close here.

**Comment by hadim** [comment]
For the record: https://github.com/docker/for-mac/issues/7440

**Comment by jakirkham** [comment]
Interesting am on a Mac, but am using [Rancher Desktop]( https://rancherdesktop.io ). This is what I see

```bash
$ docker run --rm -ti quay.io/condaforge/linux-anvil-cos7-x86_64:latest ls -la /home/conda/
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
total 24
drwx------ 2 conda conda 4096 Oct  1 22:35 .
drwxr-xr-x 1 root  root  4096 Oct  1 22:35 ..
-rw-r--r-- 1 conda conda   18 Nov 24  2021 .bash_logout
-rw-r--r-- 1 conda conda  193 Nov 24  2021 .bash_profile
-rw-r--r-- 1 conda conda  231 Nov 24  2021 .bashrc
-rw-r--r-- 1 conda conda   75 Oct  1 22:35 .condarc
```

So agree it looks like a Docker Desktop specific bug

**Comment by hadim** [comment]
Switching to Rancher now :-)

**Comment by hadim** [comment]
It's actually more a docker emulation engine question than docker versus rancher.

When I enable the Rosetta emulation (in order to run linux-64 build) then I get the same issue as above.

**Comment by hadim** [comment]
xref with 

- https://github.com/conda-forge/staged-recipes/issues/26779
- https://github.com/conda-forge/staged-recipes/issues/26781

**Comment by jakirkham** [comment]
Interesting when using the `aarch64` container on my Mac, don't see the issue either

```bash
$ docker run --rm -ti quay.io/condaforge/linux-anvil-aarch64 ls -la /home/conda/
total 24
drwx------ 2 conda conda 4096 Oct  2 00:19 .
drwxr-xr-x 1 root  root  4096 Oct  2 00:19 ..
-rw-r--r-- 1 conda conda   18 Nov 24  2021 .bash_logout
-rw-r--r-- 1 conda conda  193 Nov 24  2021 .bash_profile
-rw-r--r-- 1 conda conda  231 Nov 24  2021 .bashrc
-rw-r--r-- 1 conda conda   75 Oct  2 00:19 .condarc
```

So could be some corner case. Not really sure

**Comment by hadim** [comment]
I think it only happens when the host is on a different arch. This is when Rosetta is used.
