### ISSUE TITLE
Docker image conda-forge-x86_64?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/docker-images#33]
We have a Docker image on Docker Hub called `conda-forge-x86_64`. It hasn't seen any pushes in 5mos, it has only a handful of pulls (17), was manually pushed, and AFAICT is unused. Few questions.

1. What is it?
2. Do we need it?
3. If we don't need it, can it be removed?

**Comment by jjhelmus** [comment]
I believe `conda-forge-x86_64` was a Docker image based upon CentOS5 that I made a long time ago.  I believe it can be removed.

**Comment by jakirkham** [comment]
Would you like to do the honors?

**Comment by jjhelmus** [comment]
Image removed.  Thanks @jakirkham

**Comment by jakirkham** [comment]
Great. Thanks @jjhelmus.
