### ISSUE TITLE
License MIT vs BSD 3-Clause

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/docker-images#40]
The license file added here was MIT. Though typically we use BSD 3-Clause with source code. Are we happy with MIT license here or do we wish to switch it to BSD 3-Clause?

cc @conda-forge/core

**Comment by scopatz** [comment]
I'd really prefer BSD 3-clause :)

**Comment by pelson** [comment]
BSD-3 throughout please. 👍

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/docker-images/pull/45 ).
