### ISSUE TITLE
Would binaries built on centos:6 work fine on Ubuntu-16.04 ?

### ISSUE THREAD

**Issue by abhi18av** [conda-forge/docker-images#50]
Hi conda-forge team,

I was wondering that since you're using `centos:6` as the basis for the docker container - wouldn't this cause problems with the software meant to be run and built on Ubuntu?

Excuse my ignorance, since I'm new to a lot of stuff here but please do answer this question, I'm curios.

**Comment by jakirkham** [comment]
> Would binaries built on centos:6 work fine on Ubuntu-16.04?

Generally yes.

The main issue with Linux compatibility is ensuring that software is built on a system with a version of glibc that is compatible. In practice this mean the glibc version used to build the software sets a lower limit on the allowed version of glibc. CentOS 6 provides glibc 2.12, which is one of the older versions of glibc around (hence why it is used). Ubuntu 16.04 provides glibc 2.23. So anything built here should work fine in terms of glibc requirements.

There are other things that get linked in like `libstdc++`. However we build with an ancient copy of `gcc`. So in practice our requirements on this front are minimal enough to be satisfied by the OS. There are some trick when building software with different versions of `gcc` (e.g. 4 vs. 5), but the underlying `libstdc++` library is backwards compatible. So it shouldn't result in any issues running our packages.

That said, it is possible if you are relying on things from `yum` that there *could* be a discrepancy between systems. Though I don't know of any reports about this causing issues in practice. In the long run, it looks like we will be wrapping up `yum` packages for use with `conda` to avoid even this potential issue.

**Comment by isuruf** [comment]
If there is an issue in Ubuntu 16.04, please reopen this
