### ISSUE TITLE
Can't yum install anymore

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/docker-images#57]
Since a recent update our conda package building pipe line broke.

Specifically, it fails on:
```bash
➜  ~ docker run -it condaforge/linux-anvil
(root) [conda@9e93de846f43 ~]$ yum install -y devtoolset-2-gcc-gfortran
Loaded plugins: fastestmirror, ovl
ovl: Error while doing RPMdb copy-up:
[Errno 13] Permission denied: '/var/lib/rpm/Conflictname'
You need to be root to perform this command.
```

**Comment by jakirkham** [comment]
Looks like the feedstock in question has not been re-rendered in along time. Please re-render with `conda-smithy` 2.4.5.

**Comment by basnijholt** [comment]
Actually, it is not for `conda-forge`, but to build the latest master `conda` [on our own CI](https://gitlab.kwant-project.org/kwant/kwant/blob/master/.gitlab-ci.yml#L94), but we use `condaforge/linux-anvil` to do so.

But looking at the conda-forge CI files I can probably find out what the problem is 👍

**Comment by jakirkham** [comment]
Ah ok. Well the issue is we no longer run as `root`. So you need to use `sudo`. This only works with `yum`. If you need to use `sudo` on more things, would inherit from our Docker image and adjust what `sudo` can be used with.

**Comment by basnijholt** [comment]
Great, [I just changed it to](https://gitlab.kwant-project.org/kwant/kwant/merge_requests/200/diffs?commit_id=2589dfb98d20d985032e4d5ea537993ec5e554ff):
```
/usr/bin/sudo -n yum install -y devtoolset-2-gcc-gfortran
```
and all works now.

Thanks for your help!
