### ISSUE TITLE
avoid devtoolset's sudo

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/docker-images#61]
It is sometimes convenient to use the `condaforge/linux-anvil` container locally (i.e. without a  feedstock) for development and testing.  Of course, one occasionally needs to use `sudo` within the container.

Confusingly, `devtoolset-2` installs its own version of `sudo` (or a wrapper of it?):

```bash
$ which sudo
/opt/rh/devtoolset-2/root/usr/bin/sudo
```

That version of `sudo` is first on the container's `PATH`, but unfortunately it seems to be broken, so commands like the following will fail:

```
$ sudo yum install libX11-devel
```

(It rejects a blank password.)

The correct alternative is to use the system's original version: `/usr/bin/sudo`

```
$ /usr/bin/sudo yum install libX11-devel
```

But most users probably wouldn't guess to try that.  Is there some way we can make plain `sudo` work?  Possibilities:

1. Delete `/opt/rh/devtoolset-2/root/usr/bin/sudo`
2. Move `/usr/bin` ahead of `/opt/rh/devtoolset-2/root/usr/bin` on the path
3. `cd /opt/conda/bin && ln -s /usr/bin/sudo` (since `/opt/conda/bin` is already first on the `PATH`)

I guess I prefer option 1.  Thoughts?

**Comment by jakirkham** [comment]
Just an update here, we do plan on switching to Anaconda's new compilers. At which point, it would be reasonable to eliminate `devtoolset`. This would also solve the problem.

**Comment by jakirkham** [comment]
As we have long since switched to our own compilers and no longer use `devtoolset` compilers, this should no longer be an issue.
