### ISSUE TITLE
linux-anvil not starting/building

### ISSUE THREAD

**Issue by Try2Code** [conda-forge/docker-images#66]
Hi!

I'd like to use the linux-anvil image to debug, why the a pkg I am working on, does not build correctly. But

1. I cannot run the docker image grom docker-hub
2. I cannot build the docker image myself using the Dockerfile from this repo

1) when i run ```docker run -it condaforge/linux-anvil /bin/bash``` I get a return code 139 - that's it. Other images run without problems. That's why I tried to build it myself, but
2) when building I can this 
```Sending build context to Docker daemon   7.68kB
Step 1/15 : FROM centos:6
 ---> 70b5d81549ec
Step 2/15 : MAINTAINER conda-forge <conda-forge@googlegroups.com>
 ---> Using cache
 ---> c90459fe5325
Step 3/15 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 20d6b327c60c
Step 4/15 : ADD http://tycho.usno.navy.mil/timer.html /opt/docker/etc/timestamp
Downloading [==================================================>]     561B/561B
 ---> a9b19bb103bc
Step 5/15 : RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
 ---> Running in d5ba4e28bb3b
The command '/bin/sh -c rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6' returned a non-zero code: 139```

and again here is returncode 139. My impresion is, that this comes from within the centos:6 image. 

Does anybody have a solution for this?

thx in advance

**Comment by mbargull** [comment]
Does
```bash
docker run --rm -it centos:6 rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
```
run without issues?
`returned a non-zero code: 139` means something segfaulted, I think.
But I guess my knowledge on this is limited and there is insufficient information (Which base system? Which Docker version?).
Maybe a `centos:6` image layer got corrupted? You could try to `docker rmi centos:6 condaforge/linux-anvil` (and, if existent, any other image and container that uses the `centos:6` layers) and then `docker pull centos:6` or `docker pull condaforge/linux-anvil` again.

**Comment by Try2Code** [comment]
i use arch linux, other images run without issues. will report on other stuff when i am back home

**Comment by Try2Code** [comment]
```
docker --version 
Docker version 18.04.0-ce, build 3d479c0af6
```

the command ```docker run --rm -it centos:6 rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6``` return with exit code 139 - nothing else

removing and pulling images does not help - still getting 139

btw: ```centos:latest``` and ```centos:7``` run without problems

**Comment by sdvillal** [comment]
@Try2Code this is  you need to add ```vsyscall=emulate``` to your kernel parameters. See the small note here: https://wiki.archlinux.org/index.php/Docker#Installation

**Comment by Try2Code** [comment]
THX!! this did the trick. linux-anvil takes minutes to start, but at least it works. the centos:6  image is running withing seconds. 

anyhow - thanks for the help - problems solved

**Comment by sdvillal** [comment]
I'm also in arch and my containers start quite fast. Slowness is likely because of many files being chowned when starting the container, possibly combined with a slow - non SSD - disk. It is a well known problem and I have commented on how we solve it in #9.

**Comment by Try2Code** [comment]
I use an SSD, only. checked centos6 and 7 and multiple ubuntu images: all start under 3 seconds. I usually use 

```docker run -v ${HOME}:/${USER} -it ubuntu:18.04 /bin/bash```
