### ISSUE TITLE
Updating the `MAINTAINER`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/docker-images#7]
As our current docker image is being moved to community maintenance ( https://github.com/conda-forge/docker-images/pull/5 ), we should probably update the `MAINTAINER` tag to reflect this. Unfortunately, I don't think the `MAINTAINER` tag responds well to multiple authors and maybe that is not the way for us to go anyways. I propose the following adjustment. Feedback welcome.

    MAINTAINER conda-forge <conda-forge@googlegroups.com>

**Comment by jakirkham** [comment]
Any thoughts on this, @pelson?

**Comment by jjhelmus** [comment]
:+1: changing to the googlegroup address.

**Comment by pelson** [comment]
:+1: - sounds good to me.

**Comment by jakirkham** [comment]
Awesome. Done in PR ( https://github.com/conda-forge/docker-images/pull/11 ).

**Comment by jakirkham** [comment]
Thanks guys. It's been changed.
