### ISSUE TITLE
Rename base image

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/docker-images#8]
Sounds like we don't want to call it obvious-ci. So, let's figure out what we want to call it.

**Comment by jakirkham** [comment]
@pelson, do you have a favored name?

**Comment by pelson** [comment]
Not really. There are many running through my head (```linux```, ```linux-build```, ```conda-build```, ```linux-64```) but none that really grab me. You?

**Comment by jakirkham** [comment]
I was going to say no (honestly was thing `image` for a bit 😆), but this one might not be too bad.

`centos_devtoolset-2_64:6`

Has the OS name, explains the compiler config, mentions 64-bit only is supported, and is versioned the same way the `centos` image is. Not the most creative name, but it explains what it is without being too long (I hope).

Thoughts?

**Comment by pelson** [comment]
The only concern is the fact that a lot of implementation detail exists in the name (a bad thing rather than a good thing for me, as it means that as we change the detail, we also need to change the name).

**Comment by jakirkham** [comment]
> ...a bad thing rather than a good thing for me...

I guess I had the opposite view.

In any event, I'm not really picky on the image name, which is why I was happy to let you pick one and still am. 😄

**Comment by pelson** [comment]
So if we don't want implementation detail in the name:

```
linux-build-x86_64
```

**Comment by jakirkham** [comment]
Just as a question, if we do ever support 32-bit, would you prefer it in a separate image or the same one?

**Comment by pelson** [comment]
> if we do ever support 32-bit, would you prefer it in a separate image or the same one?

A question I was asking myself earlier on. In the obvious-ci image I went for "the same one". In the name proposed above I went for "a different image".

**Comment by jakirkham** [comment]
Could you help me understand why you want to keep them separate? I could certainly see some arguments for it, but would like to here your thoughts on it.

Something to consider (not that this is completely tied to this nor that this rules out having separate images either), we could select the architecture through [other means]( https://github.com/conda-forge/staged-recipes/pull/578/commits/2591d7c57cb47d5b76c198610b885d1c7eac8574#diff-209088c915d08aae01cca3fdc25af178R27 ). Though we may want this option in such a configuration tool no matter what we do here.

**Comment by pelson** [comment]
> Could you help me understand why you want to keep them separate?

This is simply a historically driven argument, whereby an entirely 32-bit docker image was used to produce linux-32 builds. I imagine there is detail in managing 32bit builds which would need to be handled if we were doing them on a 64bit machine (like the conda subdir / platform).

I'm guessing you are asking because you do believe that we can use the same image to produce both x86 and x64 builds?

**Comment by jakirkham** [comment]
> This is simply a historically driven argument...

Ah ok. Precedent mainly.

> I'm guessing you are asking because you do believe that we can use the same image to produce both x86 and x64 builds?

We could. That's what I did with the example image. Not saying we should or shouldn't here. Just as long as we are aware of the option.

**Comment by jakirkham** [comment]
Was trying to think of names that fit with the forge theme (I like the creative spark and wanted to keep it alive). We could call it `linux-anvil`. Just thinking of how the anvil is used as a base while some metal is being worked. If we want to add architecture, we can do that too. Just a thought.

**Comment by pelson** [comment]
🔨 Love it. ❤️   

Let's not include the arch - we can always add another image with a ```x86``` suffix if needs be.

**Comment by jakirkham** [comment]
Glad you like it. 😄

> Let's not include the arch - we can always add another image with a `x86` suffix if needs be.

Sure. Increasingly it seems 32-bit is an oddity in the Linux world. So noting it is different seems ok to me.

Will make the changes now.

**Comment by jakirkham** [comment]
Here's the PR ( https://github.com/conda-forge/docker-images/pull/9 ) for the rename.

**Comment by jakirkham** [comment]
Updated the PRs to `staged-recipes` ( https://github.com/conda-forge/staged-recipes/pull/514 ) and `conda-smithy` ( https://github.com/conda-forge/conda-smithy/pull/151 ) to reflect the name change.
